.do hla de
.do hpf hyphen.den
.TH SCOPE 1 "2021-04-27" "pep-8 Projekt" "pep-8 Projekt Handbuch" \" -*- nroff -*-
.SH NAME
scope \- X/Y-Punkt Plotter Simulation
.SH SYNOPSIS
.B scope
.RI "[\-p " port " ]"
.SH BESCHREIBUNG
Das
.BR scope 
Kommando realisiert einen TCP/IP Server. Verbindet sich ein Prozess mit
der Server,  werden die gesendeten Kommandos in ein graphishces Display 
umgesetzt.
.LP
Wird der Port nicht explizit angegeben, wartet der Server auf Port 4321
auf Verbindungen.
.PP
.BR pepsi (1)
