.do hla de
.do hpf hyphen.de
.TH SIXBIT 7 "2005-08-10" "pep-8 Projekt" "pep-8 Projekt Handbuch" \" -*- nroff -*-
.SH NAME
sixbit \- Zeichenformat des
.BR pot (1)
Assemblers für Texte.
.SH BESCHREIBUNG
Dieses Dokument beschreibt ein Format zur Kodierung von Zeichen
in jeweils sechs Bit. Damit ist es auf Systemen nützlich deren 
wortbreit ein vielfaches von secht Bit ist. Der
.BR pep8 (7) 
Prozessor erfüllt dieses Kriterium.
.ZH UMFANG
Aufgrung der Beschränkung auf nur sechs Bit, können nur Großbbuchstaben,
Ziffern, das Leerzeichen
.RI ( Space )
und die Zeichen ! " # $ % & \' ( ) * + , - . / : ; < = > ? [ \\ ] ^ _
kodiert werden.
.SH KODETABELLE
Alle Werte in okaler Notation. Die signifikate Stelle ist vertikal 
aufgetragen.
.RS
.LP
.TS
c|c c c c c c c c
_|_ _ _ _ _ _ _ _
c|c c c c c c c c .
	0	1	2	3	4	5	6	7
0		!	"	#	$	%	&	'
1	(	)	*	+	,	-	.	/
2	0	1	2	3	4	5	6	7
3	8	9	:	;	<	 = 	>	?
4	@	A	B	C	D	E	F	G
5	H	I	J	K	L	M	N	O
6	P	Q	R	S	T	U	V	W
7	X	Y	Z	[	\\	]	^	 _ 
.TE
.RE
.SH KONVERSION
Um 
.I sixbit
Zeichen in ACSII umzuwandeln muß zum Kodewert 32 (40 oktal) addiert werden.
.SH SIEHE AUCH
.BR pot (5)
